name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Create temporary config.yaml
        run: |
          cat <<EOF > config.yaml
          telegram:
            session_name: "ci_session"
            api_id: 123456
            api_hash: "fake_hash"
          channels:
            - "@FakeChannel"
          EOF

      - name: Run unit tests
        run: |
          pytest tests/

      - name: Run pipeline (mock config)
        run: |
          python -m scripts.run_pipeline || echo "Skip run_pipeline due to fake API"
